dist: xenial
language: ruby
rvm:
- 2.6.5
before_script:
- echo -e "Host railsexpress.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 ./railsexpress-key
- ssh-add ./railsexpress-key
- cat ./docker-token | docker login -u stkaes --password-stdin
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_65aa0e9e329e_key -iv $encrypted_65aa0e9e329e_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
jobs:
  include:
    - name: package-focal
      script:
        - docker pull ubuntu:20.04
        - bundle exec rake package:focal:all
    - name: package-bionic
      script:
        - docker pull ubuntu:18.04
        - bundle exec rake package:bionic:all
    - name: package-xenial
      script:
        - docker pull ubuntu:16.04
        - bundle exec rake package:xenial:all
    - name: docker-images
      script:
        # build docker images and upload them to docker hub
        - bundle exec rake build upload
