services:
  memcache:
    container_name: memcache
    image: memcached:1.6

  logjamdb:
    container_name: logjamdb
    image: mongo:4.4-focal
    command: mongod
    volumes:
      - ~/data/db.logjam:/data/db
    ports:
      - "27017:27017"

  demo:
    container_name: logjam-demo
    image: stkaes/logjam-app
    ports:
      # logjam web ui
      - "80:80"
      # logjam live stream data
      - "8080:8080"
      # logjam msgs router port
      - "9604:9604"
      # logjam msgs pull port
      - "9605:9605"
      # logjam device pub port
      - "9606:9606"
      # logjam device stats port
      - "9621:9621"
      # logjam frontend data port
      - "9705:9705"
      # importer prometheus metrics
      - "9610:9610"
      # exporter prometheus metrics
      - "8081:8081"
      # device prometheus metrics
      - "8082:8082"
    tty: true
    environment:
      - LOGJAMDB_NAME=logjamdb
      - LOGJAMCACHE_NAME=memcache
      - LOGJAM_ENV=production
      - LOGJAM_USE_CACHE=0
      - LOGJAM_EXPORTER_INSTALL=0
    env_file:
      - "logjam.env"
