version: '2'

services:
  memcache:
    container_name: memcache
    image: memcached:1.5.19

  logjamdb:
    container_name: logjamdb
    image: percona/percona-server-mongodb:4.2.3
    command: mongod
    volumes:
      - ~/data/db.logjam:/data/db
    ports:
      - "27017:27017"

  demo:
    container_name: logjam-demo
    image: stkaes/logjam-app
    ports:
      - "80:80"
      - "8080:8080"
      - "9604:9604"
      - "9605:9605"
      - "9705:9705"
    tty: true
    environment:
      - LOGJAMDB_NAME=logjamdb
      - LOGJAMCACHE_NAME=memcache
      - LOGJAM_ENV=production
      - LOGJAM_USE_CACHE=0
    env_file:
      - "logjam.env"
